// ==========================================================
// verrah/controllers/deposit.js
//
// VERRAH COSMETICS
// DAILY CASH SALE DEPOSIT CONTROLLER
// ==========================================================

const dailyCashDepositService =
    require("../services/dailyCashDepositService");


// ==========================================================
// ERROR HELPER
// ==========================================================

function getErrorMessage(err) {

    if (!err) {
        return "Unable to process the deposit.";
    }

    return (
        err.message ||
        "Unable to process the deposit."
    );
}


// ==========================================================
// RENDER DEPOSIT PAGE
//
// GET /deposit/:id
//
// :id = dailyCashSales._id
// ==========================================================

async function showDeposit(req, res) {

    try {

        const deposit =
            await dailyCashDepositService.getDeposit(
                req.params.id
            );

        return res.render(
            "deposit",
            {
                deposit,
                user: req.user,
                error: null
            }
        );

    } catch (err) {

        return res.status(400).render(
            "error",
            {
                statusCode: 400,
                title: "Bad Request",
                message: getErrorMessage(err),
                user: req.user
            }
        );
    }
}


// ==========================================================
// INITIATE M-PESA STK PUSH
//
// POST /deposit/:id/pay
// ==========================================================

async function initiatePayment(req, res) {

    try {

        const {
            phone,
            amount
        } = req.body;

        const result =
            await dailyCashDepositService.initiateDeposit(
                {
                    saleId: req.params.id,
                    phone,
                    amount
                }
            );

        return res.json({
            success: true,
            ...result
        });

    } catch (err) {

        return res.status(400).json({
            success: false,
            message: getErrorMessage(err)
        });
    }
}


// ==========================================================
// M-PESA CALLBACK
//
// POST /deposit/mpesa/callback
// ==========================================================

async function mpesaCallback(req, res) {

    try {

        const callback =
            await dailyCashDepositService.handleCallback(
                req.body
            );

        // --------------------------------------------------
        // Successful STK callback
        // --------------------------------------------------

        if (
            callback.success &&
            callback.receiptNumber
        ) {

            /*
             * The AccountReference generated by the service is:
             *
             * CASH-XXXXXXXX
             *
             * Recover the dailyCashSales._id from it.
             */

            const accountReference =
                req.body &&
                req.body.Body &&
                req.body.Body.stkCallback &&
                req.body.Body.stkCallback.CallbackMetadata;

            // The exact sale ID should be associated with the
            // CheckoutRequestID before marking the sale deposited.
        }

        return res.json({
            ResultCode: 0,
            ResultDesc: "Accepted"
        });

    } catch (err) {

        console.error(
            "Daily cash M-Pesa callback error:",
            err
        );

        return res.json({
            ResultCode: 0,
            ResultDesc: "Accepted"
        });
    }
}


// ==========================================================
// EXPORTS
// ==========================================================

module.exports = {
    showDeposit,
    initiatePayment,
    mpesaCallback
};