// ==========================================================
// models/institutionalTransfers.js
// INSTITUTIONAL TRANSFER ADMISSION
// ==========================================================
//
// THIS MODEL DOES NOT GENERATE REGISTRATION NUMBERS.
//
// Registration numbers are generated only by:
//     services/studentAdmissionService.js
// ==========================================================

const mongoose = require("mongoose");

const TRANSFER_STATUSES = [
  "pending",
  "approved",
  "rejected",
  "cancelled",
  "completed"
];

const TRANSFER_TYPES = [
  "institutional-transfer",
  "inter-university-transfer",
  "inter-college-transfer",
  "programme-transfer"
];

const institutionalTransferSchema = new mongoose.Schema(
  {
    student: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Student",
      default: null,
      index: true
    },

    transferApplicationNumber: {
      type: String,
      trim: true,
      unique: true,
      sparse: true,
      index: true
    },

    transferType: {
      type: String,
      enum: TRANSFER_TYPES,
      default: "institutional-transfer"
    },

    status: {
      type: String,
      enum: TRANSFER_STATUSES,
      default: "pending",
      index: true
    },

    studentName: {
      type: String,
      required: true,
      trim: true
    },

    previousInstitution: {
      type: String,
      required: true,
      trim: true
    },

    previousInstitutionCode: {
      type: String,
      trim: true
    },

    previousRegistrationNumber: {
      type: String,
      trim: true
    },

    previousProgramme: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Programme"
    },

    previousProgrammeName: {
      type: String,
      trim: true
    },

    previousYearOfStudy: {
      type: Number,
      min: 1
    },

    programme: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Programme",
      required: true,
      index: true
    },

    academicYear: {
      type: String,
      required: true,
      trim: true,
      match: [
        /^\d{4}\/\d{2}$/,
        "Academic year must use YYYY/YY."
      ],
      index: true
    },

    semester: {
      type: String,
      required: true,
      enum: [
        "September-December",
        "January-April",
        "May-August"
      ]
    },

    academicSession: {
      type: String,
      required: true,
      trim: true,
      index: true
    },

    yearOfStudy: {
      type: Number,
      min: 1
    },

    creditsTransferred: {
      type: Number,
      min: 0,
      default: 0
    },

    creditsAccepted: {
      type: Number,
      min: 0,
      default: 0
    },

    reason: {
      type: String,
      trim: true
    },

    applicationDate: {
      type: Date,
      default: Date.now
    },

    transferDate: Date,

    /*
     * Assigned by studentAdmissionService.
     */
    registrationNumber: {
      type: String,
      trim: true,
      index: true
    },

    registrationSequence: {
      type: Number,
      min: 1,
      index: true
    },

    approvedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Staff"
    },

    approvalDate: Date,

    approvalRemarks: {
      type: String,
      trim: true
    },

    rejectionReason: {
      type: String,
      trim: true
    },

    cancellationReason: {
      type: String,
      trim: true
    },

    documents: {
      type: [
        {
          name: { type: String, trim: true },
          file: { type: String, trim: true },
          uploadedAt: { type: Date, default: Date.now }
        }
      ],
      default: []
    },

    remarks: {
      type: String,
      trim: true
    }
  },
  {
    timestamps: true
  }
);

institutionalTransferSchema.index({
  student: 1,
  status: 1
});

institutionalTransferSchema.index({
  previousInstitution: 1,
  previousRegistrationNumber: 1
});

institutionalTransferSchema.methods.markCompleted =
async function(studentId, registrationNumber, registrationSequence) {

  if (!studentId) {
    throw new Error("Student ID is required.");
  }

  if (!registrationNumber) {
    throw new Error(
      "Registration number must be generated by studentAdmissionService."
    );
  }

  this.student = studentId;
  this.registrationNumber = registrationNumber;
  this.registrationSequence = registrationSequence;
  this.status = "completed";
  this.transferDate =
    this.transferDate || new Date();

  return this.save();
};

module.exports = mongoose.model(
  "InstitutionalTransfer",
  institutionalTransferSchema
);

module.exports.TRANSFER_STATUSES =
  TRANSFER_STATUSES;

module.exports.TRANSFER_TYPES =
  TRANSFER_TYPES;
