// ==========================================================
// models/kuccpsPlacements.js
// KUCCPS PLACEMENT
// ==========================================================
//
// THIS MODEL DOES NOT GENERATE REGISTRATION NUMBERS.
//
// Registration numbers are generated only by:
//     services/studentAdmissionService.js
//
// The placement stores the number assigned by that service.
// ==========================================================

const mongoose = require("mongoose");

const PLACEMENT_STATUSES = [
  "placed",
  "contacted",
  "admitted",
  "registered",
  "declined",
  "deferred",
  "cancelled"
];

const GENDERS = [
  "male",
  "female",
  "other"
];

const kuccpsPlacementSchema = new mongoose.Schema(
  {
    kuccpsIndexNumber: {
      type: String,
      required: true,
      trim: true,
      index: true
    },

    kuccpsPlacementNumber: {
      type: String,
      trim: true,
      index: true
    },

    kuccpsApplicationNumber: {
      type: String,
      trim: true
    },

    name: {
      type: String,
      required: true,
      trim: true
    },

    nationalID: {
      type: String,
      trim: true
    },

    gender: {
      type: String,
      enum: GENDERS
    },

    dateOfBirth: Date,

    telephone: {
      type: String,
      trim: true
    },

    email: {
      type: String,
      trim: true,
      lowercase: true
    },

    kcseIndexNumber: {
      type: String,
      trim: true
    },

    kcseYear: {
      type: Number,
      min: 1900
    },

    kcseGrade: {
      type: String,
      trim: true
    },

    programme: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Programme",
      required: true,
      index: true
    },

    university: {
      type: String,
      trim: true
    },

    campus: {
      type: String,
      trim: true
    },

    academicYear: {
      type: String,
      required: true,
      trim: true,
      match: [
        /^\d{4}\/\d{2}$/,
        "Academic year must use YYYY/YY."
      ],
      index: true
    },

    semester: {
      type: String,
      required: true,
      enum: [
        "September-December",
        "January-April",
        "May-August"
      ]
    },

    academicSession: {
      type: String,
      required: true,
      trim: true,
      index: true
    },

    /*
     * These are assigned by studentAdmissionService.
     * They are never calculated here.
     */
    registrationNumber: {
      type: String,
      trim: true,
      unique: true,
      sparse: true,
      index: true
    },

    registrationSequence: {
      type: Number,
      min: 1,
      index: true
    },

    student: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Student",
      default: null,
      index: true
    },

    status: {
      type: String,
      enum: PLACEMENT_STATUSES,
      required: true,
      default: "placed",
      index: true
    },

    placementDate: Date,
    reportingDate: Date,
    admittedAt: Date,
    registeredAt: Date,

    intake: {
      type: String,
      trim: true
    },

    remarks: {
      type: String,
      trim: true
    }
  },
  {
    timestamps: true
  }
);

kuccpsPlacementSchema.index(
  {
    kuccpsIndexNumber: 1,
    academicYear: 1
  },
  {
    unique: true
  }
);

kuccpsPlacementSchema.index({
  registrationSequence: 1,
  academicYear: 1
});

kuccpsPlacementSchema.methods.markRegistered =
async function(studentId, registrationNumber, registrationSequence) {

  if (!studentId) {
    throw new Error("Student ID is required.");
  }

  if (!registrationNumber) {
    throw new Error(
      "Registration number must be generated by studentAdmissionService."
    );
  }

  this.student = studentId;
  this.registrationNumber = registrationNumber;
  this.registrationSequence = registrationSequence;
  this.status = "registered";
  this.registeredAt = new Date();

  return this.save();
};

kuccpsPlacementSchema.virtual("isRegistered").get(
  function() {
    return (
      this.status === "registered" &&
      this.student !== null
    );
  }
);

kuccpsPlacementSchema.virtual("isPendingRegistration").get(
  function() {
    return (
      this.status !== "registered" &&
      this.status !== "cancelled"
    );
  }
);

kuccpsPlacementSchema.set("toJSON", {
  virtuals: true
});

kuccpsPlacementSchema.set("toObject", {
  virtuals: true
});

module.exports = mongoose.model(
  "KuccpsPlacement",
  kuccpsPlacementSchema
);

module.exports.PLACEMENT_STATUSES =
  PLACEMENT_STATUSES;

module.exports.GENDERS =
  GENDERS;
