// ==========================================================
// controllers/update/booleanController.js
// BOOLEAN ANIMAL CONTROLLER
// ==========================================================
//
// PURPOSE
// ----------------------------------------------------------
//
// Handles Boolean toggle requests generated by:
//
//     views/update/boolean.ejs
//
// IMPORTANT:
// ----------------------------------------------------------
//
// boolean.ejs is an INCLUDE.
//
// It is NOT rendered by this controller.
//
// The parent page remains:
//
//     views/update.ejs
//
// TOGGLE ROUTE:
//
//     POST /dairy/:animalId/boolean/:field
//
// PARAMETERS:
//
//     :animalId
//         = MongoDB _id of the eligible animal
//
//     :field
//         = Boolean field name from the Dairy schema
//
// ==========================================================


const updateService =
    require("../../services/update");


// ==========================================================
// TOGGLE BOOLEAN
// ==========================================================
//
// POST:
//
//     /dairy/:animalId/boolean/:field
//
// PARAMETERS:
//
//     animalId
//     field
//
// The service performs the actual Boolean toggle.
//
// ==========================================================

exports.toggleBoolean =
async function (
    req,
    res
) {

    try {

        // ==================================================
        // AUTHENTICATION
        // ==================================================

        if (
            !req.session ||
            !req.session.user
        ) {

            return res
                .status(401)
                .json({

                    success:
                        false,

                    message:
                        "Unauthorized"

                });

        }


        // ==================================================
        // ANIMAL ID
        // ==================================================

        const animalId =
            req.params.animalId;


        if (!animalId) {

            return res
                .status(400)
                .json({

                    success:
                        false,

                    message:
                        "Animal ID is required."

                });

        }


        // ==================================================
        // BOOLEAN FIELD
        // ==================================================
        //
        // The field comes directly from the URL:
        //
        //     /boolean/:field
        //
        // Example:
        //
        //     /boolean/isMilking
        //
        // ==================================================

        const field =
            req.params.field;


        if (
            typeof field !== "string" ||
            !field.trim()
        ) {

            return res
                .status(400)
                .json({

                    success:
                        false,

                    message:
                        "Boolean field is required."

                });

        }


        // ==================================================
        // TOGGLE THROUGH SERVICE
        // ==================================================
        //
        // The service is responsible for:
        //
        //     1. validating the Boolean schema field
        //     2. finding the animal
        //     3. verifying animal eligibility
        //     4. toggling the current value
        //     5. saving the Dairy document
        //
        // ==================================================

        const result =
            await updateService.toggleBoolean(
                animalId,
                field.trim()
            );


        // ==================================================
        // SUCCESS
        // ==================================================

        return res
            .status(200)
            .json({

                success:
                    true,

                animalId:
                    String(
                        animalId
                    ),

                field:
                    result.field,

                value:
                    result.value

            });

    } catch (err) {

        console.error(
            "TOGGLE BOOLEAN ERROR:",
            err
        );


        // ==================================================
        // SERVICE ERROR WITH STATUS
        // ==================================================

        if (
            err &&
            err.status
        ) {

            return res
                .status(
                    err.status
                )
                .json({

                    success:
                        false,

                    message:
                        err.message

                });

        }


        // ==================================================
        // ANIMAL NOT FOUND
        // ==================================================

        if (
            err &&
            err.message ===
            "Dairy animal not found."
        ) {

            return res
                .status(404)
                .json({

                    success:
                        false,

                    message:
                        err.message

                });

        }


        // ==================================================
        // SERVER ERROR
        // ==================================================

        return res
            .status(500)
            .json({

                success:
                    false,

                message:
                    "Failed to toggle Boolean."

            });

    }

};


// ==========================================================
// BOOLEAN FIELD DEFINITIONS
// ==========================================================
//
// GET:
//
//     /dairy/boolean/fields
//
// This endpoint is optional.
//
// The current boolean.ejs receives:
//
//     booleanFields
//
// directly from the parent update page.
//
// This endpoint simply exposes the same field definitions
// independently when needed.
//
// ==========================================================

exports.getBooleanFields =
async function (
    req,
    res
) {

    try {

        // ==================================================
        // AUTHENTICATION
        // ==================================================

        if (
            !req.session ||
            !req.session.user
        ) {

            return res
                .status(401)
                .json({

                    success:
                        false,

                    message:
                        "Unauthorized"

                });

        }


        // ==================================================
        // GET BOOLEAN FIELDS
        // ==================================================

        const fields =
            await updateService.getBooleanFields();


        // ==================================================
        // SUCCESS
        // ==================================================

        return res
            .status(200)
            .json({

                success:
                    true,

                fields:
                    Array.isArray(fields)
                        ? fields
                        : []

            });

    } catch (err) {

        console.error(
            "GET BOOLEAN FIELDS ERROR:",
            err
        );


        return res
            .status(500)
            .json({

                success:
                    false,

                message:
                    "Failed to load Boolean fields."

            });

    }

};