// =========================================================
// controllers/update/booleanController.js
// BOOLEAN ANIMAL CONTROLLER
// =========================================================
//
// PURPOSE
// ----------------------------------------------------------
//
// Handles boolean toggle requests generated by:
//
//     views/update/boolean.ejs
//
// IMPORTANT:
//
// boolean.ejs is an INCLUDE.
//
// It is NOT rendered by this controller.
//
// The parent page remains:
//
//     views/update.ejs
//
// ==========================================================


const updateService =
    require("../../services/update");


// ==========================================================
// TOGGLE BOOLEAN
// ==========================================================
//
// POST:
//
//     /dairy/:id/boolean/:field
//
// ==========================================================

exports.toggleBoolean =
async function (
    req,
    res
) {

    try {

        // ==================================================
        // AUTHENTICATION
        // ==================================================

        if (
            !req.session ||
            !req.session.user
        ) {

            return res
                .status(401)
                .json({

                    success:
                        false,

                    message:
                        "Unauthorized"

                });

        }


        // ==================================================
        // PARAMETERS
        // ==================================================

        const dairyId =
            req.params.id;


        const field =
            req.params.field;


        if (!dairyId) {

            return res
                .status(400)
                .json({

                    success:
                        false,

                    message:
                        "Dairy ID is required."

                });

        }


        if (!field) {

            return res
                .status(400)
                .json({

                    success:
                        false,

                    message:
                        "Boolean field is required."

                });

        }


        // ==================================================
        // TOGGLE
        // ==================================================

        const result =
            await updateService.toggleBoolean(
                dairyId,
                field
            );


        // ==================================================
        // SUCCESS
        // ==================================================

        return res
            .status(200)
            .json({

                success:
                    true,

                dairyId,

                field:
                    result.field,

                value:
                    result.value

            });

    } catch (err) {

        console.error(
            "TOGGLE BOOLEAN ERROR:",
            err
        );


        // ==================================================
        // KNOWN ERROR
        // ==================================================

        if (
            err.status
        ) {

            return res
                .status(
                    err.status
                )
                .json({

                    success:
                        false,

                    message:
                        err.message

                });

        }


        // ==================================================
        // SERVER ERROR
        // ==================================================

        return res
            .status(500)
            .json({

                success:
                    false,

                message:
                    "Failed to toggle boolean."

            });

    }

};