// ==========================================================
// controllers/update/booleanController.js
// BOOLEAN ANIMAL CONTROLLER
// ==========================================================
//
// PURPOSE
// ----------------------------------------------------------
//
// Handles Boolean updates generated by:
//
//     views/update/boolean.ejs
//
// IMPORTANT:
// ----------------------------------------------------------
//
// boolean.ejs is an INCLUDE.
//
// It is NOT rendered by this controller.
//
// The parent page remains:
//
//     views/update.ejs
//
// ROUTE:
//
//     PUT /dairy/:animalId/boolean
//
// BODY:
//
//     {
//         field: "booleanFieldName",
//         value: true
//     }
//
// ==========================================================


const updateService =
    require("../../services/update");


// ==========================================================
// UPDATE BOOLEAN
// ==========================================================
//
// PUT:
//
//     /dairy/:animalId/boolean
//
// BODY:
//
//     {
//         field,
//         value
//     }
//
// ==========================================================

exports.updateBoolean =
async function (
    req,
    res
) {

    try {

        // ==================================================
        // AUTHENTICATION
        // ==================================================

        if (
            !req.session ||
            !req.session.user
        ) {

            return res
                .status(401)
                .json({

                    success:
                        false,

                    message:
                        "Unauthorized"

                });

        }


        // ==================================================
        // ANIMAL ID
        // ==================================================

        const animalId =
            req.params.animalId;


        if (!animalId) {

            return res
                .status(400)
                .json({

                    success:
                        false,

                    message:
                        "Animal ID is required."

                });

        }


        // ==================================================
        // REQUEST BODY
        // ==================================================

        const field =
            req.body
                ? req.body.field
                : null;


        const value =
            req.body
                ? req.body.value
                : null;


        // ==================================================
        // FIELD VALIDATION
        // ==================================================

        if (
            typeof field !== "string" ||
            !field.trim()
        ) {

            return res
                .status(400)
                .json({

                    success:
                        false,

                    message:
                        "Boolean field is required."

                });

        }


        // ==================================================
        // VALUE VALIDATION
        //
        // Only actual Boolean values are accepted.
        //
        // This deliberately prevents strings such as:
        //
        //     "true"
        //     "false"
        //
        // from being accidentally stored.
        // ==================================================

        if (
            typeof value !== "boolean"
        ) {

            return res
                .status(400)
                .json({

                    success:
                        false,

                    message:
                        "Boolean value must be true or false."

                });

        }


        // ==================================================
        // UPDATE THROUGH SERVICE
        // ==================================================

        const result =
            await updateService.updateBoolean(
                animalId,
                field.trim(),
                value,
                req.session.user
            );


        // ==================================================
        // SUCCESS
        // ==================================================

        return res
            .status(200)
            .json({

                success:
                    true,

                animalId:

                    String(
                        animalId
                    ),

                field:
                    result.field,

                value:
                    result.value

            });

    } catch (err) {

        console.error(
            "UPDATE BOOLEAN ERROR:",
            err
        );


        // ==================================================
        // SERVICE ERROR WITH STATUS
        // ==================================================

        if (
            err &&
            err.status
        ) {

            return res
                .status(
                    err.status
                )
                .json({

                    success:
                        false,

                    message:
                        err.message

                });

        }


        // ==================================================
        // NOT FOUND
        // ==================================================

        if (
            err &&
            (
                err.message ===
                "Animal not found."
            )
        ) {

            return res
                .status(404)
                .json({

                    success:
                        false,

                    message:
                        err.message

                });

        }


        // ==================================================
        // SERVER ERROR
        // ==================================================

        return res
            .status(500)
            .json({

                success:
                    false,

                message:
                    "Failed to update boolean."

            });

    }

};


// ==========================================================
// BOOLEAN FIELD DEFINITIONS
// ==========================================================
//
// GET:
//
//     /dairy/boolean/fields
//
// This supplies boolean.ejs with the available Boolean
// fields for its first expandable card/dropdown.
//
// ==========================================================

exports.getBooleanFields =
async function (
    req,
    res
) {

    try {

        // ==================================================
        // AUTHENTICATION
        // ==================================================

        if (
            !req.session ||
            !req.session.user
        ) {

            return res
                .status(401)
                .json({

                    success:
                        false,

                    message:
                        "Unauthorized"

                });

        }


        // ==================================================
        // GET FIELD DEFINITIONS
        // ==================================================

        const fields =
            await updateService.getBooleanFields();


        // ==================================================
        // SUCCESS
        // ==================================================

        return res
            .status(200)
            .json({

                success:
                    true,

                fields:
                    Array.isArray(fields)
                        ? fields
                        : []

            });

    } catch (err) {

        console.error(
            "GET BOOLEAN FIELDS ERROR:",
            err
        );


        return res
            .status(500)
            .json({

                success:
                    false,

                message:
                    "Failed to load Boolean fields."

            });

    }

};