// ==========================================================
// controllers/milkController.js
// ==========================================================
//
// PURPOSE
// ----------------------------------------------------------
// General controller for the milk module.
//
// Handles:
//
// • Milk statistics
// • Daily statistics
// • Milk sales
// • Standing orders
// • Milk pricing
// • Milking history
// • Milking status
//
// DOES NOT HANDLE:
//
// • GET  /milk
// • POST /milk
// • GET  /milk/edit/:id
// • POST /milk/:id
//
// Those belong exclusively to:
//
//     controllers/milkCollectController.js
//
// IMPORTANT FARM PRODUCTION RULE
// ----------------------------------------------------------
//
// Farm production and milk sales are FARM-SCOPED.
//
// The controller passes the authenticated user and selected
// farm to the service.
//
// The controller does NOT calculate:
//
//     • farm production
//     • farm available milk
//     • farm sales
//     • farm revenue
//
// Those calculations belong to milkService.js.
//
// ==========================================================


const mongoose =
    require("mongoose");


const milkService =
    require("../services/milkService");


// ==========================================================
// AUTHENTICATED USER
// ==========================================================
//
// Application normally uses:
//
//     req.session.user
//
// Some middleware may expose:
//
//     req.user
//
// Support both.
//
// ==========================================================

function getUser(
    req
) {

    return (
        req.session?.user ||
        req.user ||
        null
    );

}


// ==========================================================
// ADMIN CHECK
// ==========================================================

function isAdmin(
    req
) {

    const user =
        getUser(req);


    return Boolean(
        user &&
        user.role === "admin"
    );

}


// ==========================================================
// OBJECT ID VALIDATION
// ==========================================================

function isValidObjectId(
    value
) {

    return mongoose.Types.ObjectId.isValid(
        value
    );

}


// ==========================================================
// ERROR RESPONSE
// ==========================================================

function sendError(
    res,
    error,
    fallback
) {

    console.error(
        error
    );


    // ======================================================
    // BUSINESS ERRORS
    // ======================================================
    //
    // These are errors intentionally generated by
    // milkService.js.
    //
    // They are client/business-rule failures and should
    // not become generic HTTP 500 responses.
    //
    // ======================================================

    const businessErrors = [

        "MILK_USER_REQUIRED",

        "MILK_ADMIN_REQUIRED",

        "MILK_FARM_REQUIRED",

        "MILK_FARM_ACCESS_DENIED",

        "MILK_INVALID_ANIMAL",

        "MILK_NO_RECORDS",

        "MILK_TIME_CLOSED",

        "MILK_INVALID_QUANTITY",

        "MILK_DUPLICATE_RECORD",

        "MILK_ALREADY_RECORDED",

        "MILK_SAVE_FAILED",

        "MILK_NOT_FOUND",

        "MILK_INVALID_DAY",

        "MILK_INVALID_MONTH",

        "MILK_INVALID_PRICE",

        "MILK_INVALID_CUSTOMER",

        "MILK_INSUFFICIENT",

        "MILK_DAY_LOCKED",

        "MILK_INVALID_ORDER",

        "MILK_ORDER_NOT_FOUND",

        "MILK_ORDER_INACTIVE",

        "MILK_ORDER_NOT_ACTIVE",

        "MILK_ORDER_ALREADY_PROCESSED",

        "MILK_SUMMARY_NOT_FOUND"

    ];


    if (
        error?.code &&
        businessErrors.includes(
            error.code
        )
    ) {

        return res
            .status(400)
            .send(
                error.message ||
                fallback ||
                "Unable to complete the request."
            );

    }


    return res
        .status(500)
        .send(
            error?.message ||
            fallback ||
            "An error occurred."
        );

}


// ==========================================================
// GET MILK STATISTICS
// ==========================================================
//
// GET /stats
//
// Supported:
//
// /stats
//
// /stats?type=day&date=2026-08-13
//
// /stats?type=month&month=2026-08
//
// ==========================================================

exports.getMilkStats =
async function(
    req,
    res
) {

    try {

        // ==================================================
        // AUTHENTICATION
        // ==================================================

        const user =
            getUser(req);


        if (!user) {

            return res.redirect(
                "/login"
            );

        }


        // ==================================================
        // TYPE
        // ==================================================

        const type =
            req.query?.type ||
            "day";


        // ==================================================
        // DAILY STATISTICS
        // ==================================================

        if (
            type === "day"
        ) {

            const kenyaParts =
                milkService.getKenyaDateParts();


            const selectedDate =
                req.query?.date ||
                kenyaParts.date;


            const data =
                await milkService.getDailyStats(

                    selectedDate,

                    user

                );


            return res.render(
                "milkStats",
                {

                    type:
                        "day",

                    date:
                        selectedDate,

                    month:
                        "",

                    records:
                        Array.isArray(
                            data?.records
                        )
                            ? data.records
                            : [],

                    stats:
                        data?.stats ||
                        {},

                    sales:
                        Array.isArray(
                            data?.sales
                        )
                            ? data.sales
                            : [],

                    farmTotals:
                        Array.isArray(
                            data?.farmTotals
                        )
                            ? data.farmTotals
                            : [],

                    user

                }
            );

        }


        // ==================================================
        // MONTHLY STATISTICS
        // ==================================================

        if (
            type === "month"
        ) {

            const kenyaParts =
                milkService.getKenyaDateParts();


            const selectedMonth =
                req.query?.month ||
                kenyaParts.monthKey;


            const data =
                await milkService.getMonthlyStats(

                    selectedMonth,

                    user

                );


            return res.render(
                "milkStats",
                {

                    type:
                        "month",

                    date:
                        "",

                    month:
                        selectedMonth,

                    records:
                        Array.isArray(
                            data?.records
                        )
                            ? data.records
                            : [],

                    stats:
                        data?.stats ||
                        {},

                    sales:
                        Array.isArray(
                            data?.sales
                        )
                            ? data.sales
                            : [],

                    farmTotals:
                        Array.isArray(
                            data?.farmTotals
                        )
                            ? data.farmTotals
                            : [],

                    user

                }
            );

        }


        // ==================================================
        // INVALID TYPE
        // ==================================================

        return res.status(
            400
        ).render(
            "milkStats",
            {

                type:
                    "",

                date:
                    "",

                month:
                    "",

                records:
                    [],

                stats: {

                    total:
                        0,

                    production:
                        0,

                    consumed:
                        0,

                    sold:
                        0,

                    available:
                        0,

                    price:
                        0,

                    cash:
                        0,

                    revenue:
                        0,

                    locked:
                        false,

                    avg:
                        0

                },

                sales:
                    [],

                farmTotals:
                    [],

                user

            }
        );

    }

    catch (error) {

        return sendError(
            res,
            error,
            "Unable to load milk statistics."
        );

    }

};


// ==========================================================
// SAVE DAILY STATISTICS
// ==========================================================
//
// POST /stats/day
//
// ADMIN ONLY.
//
// ==========================================================

exports.saveDailyStats =
async function(
    req,
    res
) {

    try {

        const user =
            getUser(req);


        // ==================================================
        // AUTHENTICATION
        // ==================================================

        if (!user) {

            return res.redirect(
                "/login"
            );

        }


        // ==================================================
        // ADMIN ONLY
        // ==================================================

        if (
            user.role !== "admin"
        ) {

            return res.status(
                403
            ).send(
                "Only administrators can save daily statistics."
            );

        }


        // ==================================================
        // REQUEST DATA
        // ==================================================

        const day =
            req.body?.day;


        const price =
            req.body?.price;


        if (!day) {

            throw new Error(
                "Day is required."
            );

        }


        // ==================================================
        // SAVE
        // ==================================================

        await milkService.saveDailyStats({

            day,

            price,

            user

        });


        // ==================================================
        // SUCCESS
        // ==================================================

        return res.redirect(
            `/stats?type=day&date=${encodeURIComponent(day)}`
        );

    }

    catch (error) {

        return sendError(
            res,
            error,
            "Unable to save daily statistics."
        );

    }

};


// ==========================================================
// GET SALES PAGE
// ==========================================================
//
// GET /sales
//
// IMPORTANT
// ----------------------------------------------------------
//
// getSalesPageData(user) returns:
//
//     standingOrders
//     manualSales
//     farmTotals
//     currentPrice
//     totalSales
//     totalProduction
//     totalRevenue
//     availableMilk
//
// ALL of these are passed to sales.ejs.
//
// ==========================================================

exports.getSalesPage =
async function(
    req,
    res
) {

    try {

        const user =
            getUser(req);


        // ==================================================
        // AUTHENTICATION
        // ==================================================

        if (!user) {

            return res.redirect(
                "/login"
            );

        }


        // ==================================================
        // PAGE DATA
        // ==================================================

        const data =
            await milkService.getSalesPageData(
                user
            );


        // ==================================================
        // FARM TOTALS
        // ==================================================

        const farmTotals =
            Array.isArray(
                data?.farmTotals
            )
                ? data.farmTotals
                : [];


        // ==================================================
        // SELECTED FARM
        // ==================================================
        //
        // The service calculates farmTotals for all farms
        // belonging to the logged-in user.
        //
        // If the request already contains a farmId, preserve
        // it.
        //
        // Otherwise select the first available farm.
        //
        // ==================================================

        let selectedFarmId =
            req.query?.farmId ||
            "";


        if (
            !selectedFarmId &&
            farmTotals.length
        ) {

            selectedFarmId =
                farmTotals[0].farmId?.toString() ||
                "";

        }


        // ==================================================
        // RENDER
        // ==================================================

        return res.render(
            "sales",
            {

                standingOrders:
                    Array.isArray(
                        data?.standingOrders
                    )
                        ? data.standingOrders
                        : [],

                manualSales:
                    Array.isArray(
                        data?.manualSales
                    )
                        ? data.manualSales
                        : [],

                farmTotals,

                selectedFarmId,

                currentPrice:
                    Number(
                        data?.currentPrice ?? 50
                    ),

                totalSales:
                    Number(
                        data?.totalSales || 0
                    ),

                totalProduction:
                    Number(
                        data?.totalProduction || 0
                    ),

                totalRevenue:
                    Number(
                        data?.totalRevenue || 0
                    ),

                availableMilk:
                    Number(
                        data?.availableMilk || 0
                    ),

                user

            }
        );

    }

    catch (error) {

        return sendError(
            res,
            error,
            "Unable to load sales page."
        );

    }

};


// ==========================================================
// SUBMIT MANUAL SALE
// ==========================================================
//
// POST /sales/manual
//
// Required by service:
//
//     farmId
//     customerName
//     liters
//     user
//
// ==========================================================

exports.submitManualSale =
async function(
    req,
    res
) {

    try {

        const user =
            getUser(req);


        // ==================================================
        // AUTHENTICATION
        // ==================================================

        if (!user) {

            return res.redirect(
                "/login"
            );

        }


        // ==================================================
        // FARM
        // ==================================================

        const farmId =
            req.body?.farmId;


        if (
            farmId === undefined ||
            farmId === null ||
            farmId === ""
        ) {

            throw new Error(
                "A dairy farm must be selected."
            );

        }


        // ==================================================
        // CUSTOMER
        // ==================================================

        const customerName =
            typeof req.body?.customerName === "string"

                ? req.body.customerName.trim()

                : "";


        if (!customerName) {

            throw new Error(
                "Customer name is required."
            );

        }


        // ==================================================
        // LITERS
        // ==================================================

        const rawLiters =
            req.body?.liters;


        if (
            rawLiters === undefined ||
            rawLiters === null ||
            rawLiters === ""
        ) {

            throw new Error(
                "Liters are required."
            );

        }


        const liters =
            Number(
                rawLiters
            );


        if (
            !Number.isFinite(
                liters
            ) ||
            liters <= 0
        ) {

            throw new Error(
                "Liters must be a valid number greater than zero."
            );

        }


        // ==================================================
        // SAVE FARM-SCOPED SALE
        // ==================================================

        await milkService.submitManualSale({

            farmId,

            customerName,

            liters,

            user

        });


        // ==================================================
        // SUCCESS
        // ==================================================

        return res.redirect(
            `/sales?farmId=${encodeURIComponent(farmId)}&success=${encodeURIComponent("Sale recorded successfully.")}`
        );

    }

    catch (error) {

        return sendError(
            res,
            error,
            "Unable to save manual sale."
        );

    }

};


// ==========================================================
// SUBMIT STANDING ORDER SALE
// ==========================================================
//
// POST /sales/standing-order
//
// Required by service:
//
//     farmId
//     standingOrderId
//     user
//
// IMPORTANT
// ----------------------------------------------------------
//
// The quantity is NOT taken from req.body.liters.
//
// The service obtains the quantity from:
//
//     StandingOrder.liters
//
// Therefore the controller intentionally does not pass
// customerName or liters to the service.
//
// ==========================================================

exports.submitStandingOrderSale =
async function(
    req,
    res
) {

    try {

        const user =
            getUser(req);


        // ==================================================
        // AUTHENTICATION
        // ==================================================

        if (!user) {

            return res.redirect(
                "/login"
            );

        }


        // ==================================================
        // FARM
        // ==================================================

        const farmId =
            req.body?.farmId;


        if (
            farmId === undefined ||
            farmId === null ||
            farmId === ""
        ) {

            throw new Error(
                "A dairy farm must be selected."
            );

        }


        // ==================================================
        // STANDING ORDER
        // ==================================================

        const standingOrderId =
            req.body?.standingOrderId;


        if (!standingOrderId) {

            throw new Error(
                "Standing order was not specified."
            );

        }


        if (
            !isValidObjectId(
                standingOrderId
            )
        ) {

            throw new Error(
                "Invalid standing order."
            );

        }


        // ==================================================
        // SAVE FARM-SCOPED SALE
        // ==================================================

        await milkService.submitStandingOrderSale({

            farmId,

            standingOrderId,

            user

        });


        // ==================================================
        // SUCCESS
        // ==================================================

        return res.redirect(
            `/sales?farmId=${encodeURIComponent(farmId)}&success=${encodeURIComponent("Standing order sale recorded.")}`
        );

    }

    catch (error) {

        return sendError(
            res,
            error,
            "Unable to save standing order sale."
        );

    }

};


// ==========================================================
// UPDATE MILK PRICE
// ==========================================================
//
// POST /sales/price
//
// ADMIN ONLY.
//
// ==========================================================

exports.updateMilkPrice =
async function(
    req,
    res
) {

    try {

        const user =
            getUser(req);


        // ==================================================
        // AUTHENTICATION
        // ==================================================

        if (!user) {

            return res.redirect(
                "/login"
            );

        }


        // ==================================================
        // ADMIN ONLY
        // ==================================================

        if (
            user.role !== "admin"
        ) {

            return res.status(
                403
            ).send(
                "Only administrators can update the milk price."
            );

        }


        // ==================================================
        // PRICE
        // ==================================================

        const rawPrice =
            req.body?.price;


        const price =
            Number(
                rawPrice
            );


        if (
            !Number.isFinite(price) ||
            price < 0
        ) {

            throw new Error(
                "Milk price must be a valid number."
            );

        }


        // ==================================================
        // UPDATE
        // ==================================================

        await milkService.updateMilkPrice(
            price
        );


        // ==================================================
        // SUCCESS
        // ==================================================

        return res.redirect(
            `/sales?success=${encodeURIComponent("Milk price updated successfully.")}`
        );

    }

    catch (error) {

        return sendError(
            res,
            error,
            "Unable to update milk price."
        );

    }

};


// ==========================================================
// ADD STANDING ORDER
// ==========================================================
//
// POST /sales/standing-order/add
//
// Service fields:
//
//     customerName
//     liters
//
// ==========================================================

exports.addStandingOrder =
async function(
    req,
    res
) {

    try {

        const user =
            getUser(req);


        // ==================================================
        // AUTHENTICATION
        // ==================================================

        if (!user) {

            return res.redirect(
                "/login"
            );

        }


        // ==================================================
        // CUSTOMER
        // ==================================================

        const customerName =
            typeof req.body?.customerName === "string"

                ? req.body.customerName.trim()

                : "";


        if (!customerName) {

            throw new Error(
                "Customer name is required."
            );

        }


        // ==================================================
        // LITERS
        // ==================================================

        const liters =
            Number(
                req.body?.liters
            );


        if (
            !Number.isFinite(liters) ||
            liters <= 0
        ) {

            throw new Error(
                "Liters must be a valid number greater than zero."
            );

        }


        // ==================================================
        // CREATE ORDER
        // ==================================================

        await milkService.addStandingOrder({

            customerName,

            liters

        });


        // ==================================================
        // SUCCESS
        // ==================================================

        return res.redirect(
            `/sales?success=${encodeURIComponent("Standing order added successfully.")}`
        );

    }

    catch (error) {

        return sendError(
            res,
            error,
            "Unable to add standing order."
        );

    }

};


// ==========================================================
// OMIT STANDING ORDER
// ==========================================================
//
// POST /sales/standing-order/omit
//
// Service fields:
//
//     orderId
//     user
//
// ==========================================================

exports.omitStandingOrder =
async function(
    req,
    res
) {

    try {

        const user =
            getUser(req);


        // ==================================================
        // AUTHENTICATION
        // ==================================================

        if (!user) {

            return res.redirect(
                "/login"
            );

        }


        // ==================================================
        // ORDER ID
        // ==================================================

        const id =
            req.body?.id;


        if (!id) {

            throw new Error(
                "Standing order was not specified."
            );

        }


        if (
            !isValidObjectId(id)
        ) {

            throw new Error(
                "Invalid standing order."
            );

        }


        // ==================================================
        // OMIT
        // ==================================================

        await milkService.omitStandingOrder({

            orderId:
                id,

            user

        });


        // ==================================================
        // SUCCESS
        // ==================================================

        return res.redirect(
            `/sales?success=${encodeURIComponent("Standing order omitted.")}`
        );

    }

    catch (error) {

        return sendError(
            res,
            error,
            "Unable to omit standing order."
        );

    }

};


// ==========================================================
// GET MILKING HISTORY
// ==========================================================
//
// GET:
//
//     /milk/history/:dairyId
//
// ==========================================================

exports.getMilkingHistory =
async function(
    req,
    res
) {

    try {

        // ==================================================
        // AUTHENTICATION
        // ==================================================

        const user =
            getUser(req);


        if (!user) {

            return res.redirect(
                "/login"
            );

        }


        // ==================================================
        // DAIRY ID
        // ==================================================

        const dairyId =
            req.params?.dairyId;


        if (!dairyId) {

            return res.status(
                400
            ).send(
                "Dairy animal was not specified."
            );

        }


        if (
            !isValidObjectId(
                dairyId
            )
        ) {

            return res.status(
                400
            ).send(
                "Invalid dairy animal."
            );

        }


        // ==================================================
        // MONTH
        // ==================================================

        const month =
            typeof req.query?.month === "string"

                ? req.query.month.trim()

                : "";


        // ==================================================
        // HISTORY
        // ==================================================

        const data =
            await milkService.getMilkingHistory({

                dairyId,

                month,

                user

            });


        // ==================================================
        // RENDER
        // ==================================================

        return res.render(
            "milkingHistory",
            {

                dairy:
                    data?.dairy ||
                    null,

                records:
                    Array.isArray(
                        data?.records
                    )
                        ? data.records
                        : [],

                grouped:
                    data?.grouped ||
                    {},

                monthlyTotal:
                    Number(
                        data?.monthlyTotal || 0
                    ),

                hasData:
                    Boolean(
                        data?.hasData
                    ),

                selectedMonth:
                    month,

                user

            }
        );

    }

    catch (error) {

        console.error(
            "GET MILKING HISTORY ERROR:",
            error
        );


        return sendError(
            res,
            error,
            "Unable to load milking history."
        );

    }

};


// ==========================================================
// TOGGLE MILKING STATUS
// ==========================================================
//
// POST /milk/history/:id/status
//
// ADMIN ONLY.
//
// ==========================================================

exports.toggleMilkingStatus =
async function(
    req,
    res
) {

    try {

        const user =
            getUser(req);


        // ==================================================
        // AUTHENTICATION
        // ==================================================

        if (!user) {

            return res.redirect(
                "/login"
            );

        }


        // ==================================================
        // ADMIN ONLY
        // ==================================================

        if (
            user.role !== "admin"
        ) {

            return res.status(
                403
            ).send(
                "Only administrators can change milking status."
            );

        }


        // ==================================================
        // DAIRY ID
        // ==================================================

        const id =
            req.params?.id;


        if (!id) {

            throw new Error(
                "Dairy animal was not specified."
            );

        }


        if (
            !isValidObjectId(id)
        ) {

            throw new Error(
                "Invalid dairy animal."
            );

        }


        // ==================================================
        // TOGGLE
        // ==================================================

        await milkService.toggleMilkingStatus({

            dairyId:
                id,

            user

        });


        // ==================================================
        // SUCCESS
        // ==================================================

        return res.redirect(
            `/milk/history/${encodeURIComponent(id)}`
        );

    }

    catch (error) {

        return sendError(
            res,
            error,
            "Unable to change milking status."
        );

    }

};


// ==========================================================
// LOCK DAILY SUMMARY
// ==========================================================
//
// POST /stats/day/lock
//
// ADMIN ONLY.
//
// ==========================================================

exports.lockDay =
async function(
    req,
    res
) {

    try {

        const user =
            getUser(req);


        if (!user) {

            return res.redirect(
                "/login"
            );

        }


        if (
            user.role !== "admin"
        ) {

            return res.status(
                403
            ).send(
                "Only administrators can lock daily summaries."
            );

        }


        const day =
            req.body?.day;


        if (!day) {

            throw new Error(
                "Day is required."
            );

        }


        await milkService.lockDay(

            day,

            user

        );


        return res.redirect(
            `/stats?type=day&date=${encodeURIComponent(day)}`
        );

    }

    catch (error) {

        return sendError(
            res,
            error,
            "Unable to lock daily summary."
        );

    }

};


// ==========================================================
// UNLOCK DAILY SUMMARY
// ==========================================================
//
// POST /stats/day/unlock
//
// ADMIN ONLY.
//
// ==========================================================

exports.unlockDay =
async function(
    req,
    res
) {

    try {

        const user =
            getUser(req);


        if (!user) {

            return res.redirect(
                "/login"
            );

        }


        if (
            user.role !== "admin"
        ) {

            return res.status(
                403
            ).send(
                "Only administrators can unlock daily summaries."
            );

        }


        const day =
            req.body?.day;


        if (!day) {

            throw new Error(
                "Day is required."
            );

        }


        await milkService.unlockDay(

            day,

            user

        );


        return res.redirect(
            `/stats?type=day&date=${encodeURIComponent(day)}`
        );

    }

    catch (error) {

        return sendError(
            res,
            error,
            "Unable to unlock daily summary."
        );

    }

};


// ==========================================================
// CONTROLLER EXPORT SUMMARY
// ==========================================================
//
// The following functions belong here:
//
//     getMilkStats
//     saveDailyStats
//
//     getSalesPage
//     submitManualSale
//     submitStandingOrderSale
//     updateMilkPrice
//
//     addStandingOrder
//     omitStandingOrder
//
//     getMilkingHistory
//     toggleMilkingStatus
//
//     lockDay
//     unlockDay
//
// ----------------------------------------------------------
//
// The following functions DO NOT belong here:
//
//     getMilkPage
//     submitMilk
//     getEditMilk
//     updateMilkRecord
//
// Those belong to:
//
//     controllers/milkCollectController.js
//
// ==========================================================