// ==========================================================
// services/update/storage/code-gen.js
// STORAGE URL CODE GENERATOR SERVICE
// ==========================================================
//
// PURPOSE:
//
//     Generate and expose every storage URL currently
//     derivable from models/dairy.js.
//
// SINGLE SOURCE OF TRUTH:
//
//     models/dairy.js
//
// GENERATED URL TYPES:
//
//     1. AgroStore contents URL
//
//        /storage/:dairyId/contents/:storageId
//
//     2. AgroStore item details URL
//
//        /storage/:dairyId/contents/:storageId/details/:itemId
//
// DATA RELATIONSHIP:
//
//     Parent Dairy Farm
//         recordType = "farm"
//         code       = negative integer
//
//     AgroStore
//         recordType = "structure"
//         type       = "agroStore"
//         roomNumber = negative integer
//         assetCode  = parent Farm code
//
//     Item
//         assetCode   = parent Farm code
//         dwellNumber = AgroStore roomNumber
//
// ==========================================================

const Dairy = require(
    "../../../../models/dairy"
);

// ==========================================================
// GENERATE STORAGE URL
// ==========================================================
//
// Creates:
//
//     /storage/:dairyId/contents/:storageId
//
// ==========================================================

function generateContentsUrl(
    parentFarmId,
    storageId
) {

    return (
        `/storage/${String(parentFarmId)}` +
        `/contents/${String(storageId)}`
    );
}

// ==========================================================
// GENERATE ITEM DETAILS URL
// ==========================================================
//
// Creates:
//
//     /storage/:dairyId/contents/:storageId/details/:itemId
//
// ==========================================================

function generateItemDetailsUrl(
    parentFarmId,
    storageId,
    itemId
) {

    return (
        `/storage/${String(parentFarmId)}` +
        `/contents/${String(storageId)}` +
        `/details/${String(itemId)}`
    );
}

// ==========================================================
// GET ALL STORAGE URLS
// ==========================================================
//
// Returns all farms, AgroStores, and AgroStore items together
// with every URL generated by the storage URL system.
//
// ==========================================================

async function generateStorageUrls() {

    // ======================================================
    // FIND ALL PARENT DAIRY FARMS
    // ======================================================

    const farms = await Dairy.find({
        recordType: "farm",

        code: {
            $lt: 0
        }
    })
        .sort({
            name: 1,
            code: 1,
            _id: 1
        })
        .lean();

    // ======================================================
    // FIND ALL AGROSTORES
    // ======================================================

    const agroStores = await Dairy.find({
        recordType: "structure",

        type: "agroStore",

        roomNumber: {
            $lt: 0
        }
    })
        .sort({
            assetCode: 1,
            roomNumber: 1,
            name: 1,
            _id: 1
        })
        .lean();

    // ======================================================
    // BUILD FARM LOOKUP
    // ======================================================

    const farmByCode = new Map();

    for (const farm of farms) {

        if (
            farm.code !== null &&
            farm.code !== undefined
        ) {

            farmByCode.set(
                String(farm.code),
                farm
            );
        }
    }

    // ======================================================
    // PROCESS AGROSTORES
    // ==========================================================

    const agroStoreResults = [];

    // ======================================================
    // PROCESS ITEMS
    // ==========================================================

    const itemResults = [];

    for (const agroStore of agroStores) {

        // ==================================================
        // PARENT FARM CODE
        // ==================================================

        const parentFarmCode =
            agroStore.assetCode;

        const parentFarm =
            farmByCode.get(
                String(parentFarmCode)
            );

        // ==================================================
        // IF PARENT FARM DOES NOT EXIST
        // ==================================================
        //
        // We still expose the AgroStore so that the code
        // generator makes the broken relationship visible.
        //
        // ==================================================

        if (!parentFarm) {

            agroStoreResults.push({

                ...agroStore,

                parentFarm: null,

                parentFarmCode,

                contentsUrl: null,

                error:
                    "Parent Dairy Farm was not found."
            });

            continue;
        }

        // ==================================================
        // GENERATE AGROSTORE CONTENTS URL
        // ==================================================

        const contentsUrl =
            generateContentsUrl(
                parentFarm._id,
                agroStore._id
            );

        agroStoreResults.push({

            ...agroStore,

            parentFarm,

            parentFarmCode,

            contentsUrl,

            error: null
        });

        // ==================================================
        // FIND ITEMS BELONGING TO THIS AGROSTORE
        // ==================================================
        //
        // IMPORTANT:
        //
        // Item membership is determined by BOTH:
        //
        //     item.assetCode
        //         === parentFarm.code
        //
        // AND
        //
        //     item.dwellNumber
        //         === agroStore.roomNumber
        //
        // ==================================================

        const items = await Dairy.find({

            assetCode: parentFarm.code,

            dwellNumber: agroStore.roomNumber,

            _id: {
                $ne: agroStore._id
            }

        })
            .sort({
                name: 1,
                _id: 1
            })
            .lean();

        // ==================================================
        // GENERATE ITEM URLS
        // ==================================================

        for (const item of items) {

            const detailsUrl =
                generateItemDetailsUrl(
                    parentFarm._id,
                    agroStore._id,
                    item._id
                );

            itemResults.push({

                ...item,

                parentFarm,

                agroStore,

                parentFarmCode,

                storageId:
                    agroStore._id,

                contentsUrl,

                detailsUrl
            });
        }
    }

    // ======================================================
    // GENERATE FARM-LEVEL INFORMATION
    // ======================================================

    const farmResults = farms.map(
        farm => {

            const farmAgroStores =
                agroStoreResults.filter(
                    agroStore => {

                        return (
                            agroStore.parentFarmCode !==
                                null &&
                            agroStore.parentFarmCode !==
                                undefined &&
                            String(
                                agroStore.parentFarmCode
                            ) === String(
                                farm.code
                            )
                        );
                    }
                );

            return {

                ...farm,

                agroStoreCount:
                    farmAgroStores.length,

                agroStores:
                    farmAgroStores
            };
        }
    );

    // ======================================================
    // SUMMARY
    // ======================================================

    const validAgroStores =
        agroStoreResults.filter(
            agroStore =>
                Boolean(
                    agroStore.contentsUrl
                )
        );

    const invalidAgroStores =
        agroStoreResults.filter(
            agroStore =>
                !agroStore.contentsUrl
        );

    const summary = {

        farmCount:
            farms.length,

        agroStoreCount:
            agroStoreResults.length,

        validAgroStoreCount:
            validAgroStores.length,

        invalidAgroStoreCount:
            invalidAgroStores.length,

        itemCount:
            itemResults.length,

        contentsUrlCount:
            validAgroStores.length,

        itemDetailsUrlCount:
            itemResults.length,

        totalUrlCount:
            validAgroStores.length +
            itemResults.length
    };

    // ======================================================
    // RETURN
    // ======================================================

    return {

        farms: farmResults,

        agroStores:
            agroStoreResults,

        items:
            itemResults,

        summary
    };
}

// ==========================================================
// EXPORT
// ==========================================================

module.exports = {

    generateStorageUrls,

    generateContentsUrl,

    generateItemDetailsUrl
};