// ==========================================================
// models/financials.js
// ==========================================================
//
// FINANCIAL TRANSACTION MODEL
//
// PURPOSE
// ----------------------------------------------------------
//
// Stores individual financial transactions belonging to a
// Dairy record.
//
// Supported transaction types:
//
//     revenue
//     liability
//
// IMPORTANT
// ----------------------------------------------------------
//
// `type` is REQUIRED.
//
// There is deliberately NO default transaction type.
//
// This prevents a revenue transaction from accidentally being
// stored as a liability when some caller forgets to provide
// `type`.
//
// The `dairy` ObjectId is the authoritative relationship.
//
// `dairyCode` is only a historical snapshot of the Dairy code
// at the time the transaction was recorded.
//
// ==========================================================


const mongoose =
    require("mongoose");


// ==========================================================
// FINANCIAL TYPES
// ==========================================================
//
// Keep these values explicit and independent.
//
// revenue
//     Money earned/generated by the Dairy.
//
// liability
//     Money owed / financial obligation.
//
// ==========================================================

const FINANCIAL_TYPES = Object.freeze([

    "revenue",

    "liability"

]);


// ==========================================================
// NORMALIZE FINANCIAL TYPE
// ==========================================================
//
// Ensures:
//
//     "Revenue"   → "revenue"
//     " REVENUE " → "revenue"
//     "Liability" → "liability"
//
// Invalid / empty values return null.
//
// ==========================================================

function normalizeFinancialType(
    type
) {

    if (
        type === undefined ||
        type === null
    ) {

        return null;

    }


    const normalized =
        String(type)
            .trim()
            .toLowerCase();


    if (
        !FINANCIAL_TYPES.includes(
            normalized
        )
    ) {

        return null;

    }


    return normalized;

}


// ==========================================================
// SCHEMA
// ==========================================================

const financialSchema =
    new mongoose.Schema(

        {

            // ==================================================
            // DAIRY / ASSET
            // ==================================================
            //
            // The exact Dairy record to which this transaction
            // belongs.
            //
            // This ObjectId is authoritative.
            //
            // A transaction can therefore belong to:
            //
            //     Dairy Farm
            //     Animal
            //     Structure
            //     Facility
            //     Equipment
            //     Other Dairy asset
            //
            // ==================================================

            dairy: {

                type:
                    mongoose.Schema.Types.ObjectId,

                ref:
                    "Dairy",

                required:
                    true,

                index:
                    true

            },


            // ==================================================
            // DAIRY CODE SNAPSHOT
            // ==================================================
            //
            // Historical snapshot only.
            //
            // This must NOT be used as the primary relationship.
            //
            // The Dairy ObjectId above remains authoritative.
            //
            // ==================================================

            dairyCode: {

                type:
                    Number,

                default:
                    null

            },


            // ==================================================
            // FINANCIAL TYPE
            // ==================================================
            //
            // REQUIRED.
            //
            // IMPORTANT:
            //
            // There is intentionally NO default here.
            //
            // Previously:
            //
            //     default: "liability"
            //
            // could silently turn an incorrectly constructed
            // transaction into a liability.
            //
            // Now a missing type causes validation to fail.
            //
            // ==================================================

            type: {

                type:
                    String,

                enum:
                    FINANCIAL_TYPES,

                required:
                    true,

                index:
                    true,

                set:
                    normalizeFinancialType

            },


            // ==================================================
            // AMOUNT
            // ==================================================
            //
            // Amount represented by the transaction.
            //
            // The meaning depends exclusively on `type`.
            //
            // revenue:
            //
            //     amount = revenue
            //
            // liability:
            //
            //     amount = liability
            //
            // ==================================================

            amount: {

                type:
                    Number,

                required:
                    true,

                min:
                    0

            },


            // ==================================================
            // DESCRIPTION
            // ==================================================

            description: {

                type:
                    String,

                trim:
                    true,

                required:
                    true

            },


            // ==================================================
            // RECORDED BY
            // ==================================================

            recordedBy: {

                type:
                    mongoose.Schema.Types.ObjectId,

                ref:
                    "User",

                required:
                    true,

                index:
                    true

            },


            // ==================================================
            // RECORDED BY NAME
            // ==================================================
            //
            // Snapshot of the user's name when the transaction
            // was recorded.
            //
            // ==================================================

            recordedByName: {

                type:
                    String,

                trim:
                    true,

                default:
                    ""

            }

        },

        {

            // ==================================================
            // TIMESTAMPS
            // ==================================================

            timestamps:
                true,

            minimize:
                false

        }

    );


// ==========================================================
// VALIDATE TYPE EXPLICITLY
// ==========================================================
//
// This provides an additional guard against empty or malformed
// transaction types.
//
// ==========================================================

financialSchema.path("type").validate(

    function(value) {

        return Boolean(
            normalizeFinancialType(value)
        );

    },

    "Financial transaction type must be either 'revenue' or 'liability'."

);


// ==========================================================
// NORMALIZE TYPE BEFORE VALIDATION
// ==========================================================
//
// Ensures all newly saved documents use the canonical lowercase
// representation.
//
// ==========================================================

financialSchema.pre(
    "validate",
    function(next) {

        const normalizedType =
            normalizeFinancialType(
                this.type
            );


        if (!normalizedType) {

            return next(
                new Error(
                    "Financial transaction type must be either 'revenue' or 'liability'."
                )
            );

        }


        this.type =
            normalizedType;


        next();

    }
);


// ==========================================================
// NORMALIZE TYPE ON FIND-ONE-AND-UPDATE
// ==========================================================
//
// Protects updates performed through:
//
//     findOneAndUpdate()
//     findByIdAndUpdate()
//
// ==========================================================

financialSchema.pre(
    "findOneAndUpdate",
    function(next) {

        const update =
            this.getUpdate() || {};


        const type =
            update.type ??
            update.$set?.type;


        if (
            type !== undefined
        ) {

            const normalizedType =
                normalizeFinancialType(
                    type
                );


            if (!normalizedType) {

                return next(
                    new Error(
                        "Financial transaction type must be either 'revenue' or 'liability'."
                    )
                );

            }


            if (
                update.$set
            ) {

                update.$set.type =
                    normalizedType;

            } else {

                update.type =
                    normalizedType;

            }

        }


        next();

    }
);


// ==========================================================
// DAIRY + TYPE
// ==========================================================
//
// Efficient retrieval of:
//
//     all revenue for one Dairy
//
//     all liabilities for one Dairy
//
// ==========================================================

financialSchema.index({

    dairy:
        1,

    type:
        1

});


// ==========================================================
// DAIRY + TYPE + CREATED AT
// ==========================================================
//
// Supports date-filtered financial reporting.
//
// ==========================================================

financialSchema.index({

    dairy:
        1,

    type:
        1,

    createdAt:
        -1

});


// ==========================================================
// TYPE + CREATED AT
// ==========================================================
//
// Supports global revenue/liability reporting.
//
// ==========================================================

financialSchema.index({

    type:
        1,

    createdAt:
        -1

});


// ==========================================================
// RECORDED BY + CREATED AT
// ==========================================================
//
// Supports audit/history queries.
//
// ==========================================================

financialSchema.index({

    recordedBy:
        1,

    createdAt:
        -1

});


// ==========================================================
// STATIC: GET FINANCIAL TYPES
// ==========================================================

financialSchema.statics.getFinancialTypes =
function() {

    return [
        ...FINANCIAL_TYPES
    ];

};


// ==========================================================
// STATIC: NORMALIZE FINANCIAL TYPE
// ==========================================================

financialSchema.statics.normalizeFinancialType =
function(type) {

    return normalizeFinancialType(
        type
    );

};


// ==========================================================
// STATIC: CHECK FINANCIAL TYPE
// ==========================================================

financialSchema.statics.isFinancialType =
function(type) {

    return Boolean(
        normalizeFinancialType(
            type
        )
    );

};


// ==========================================================
// STATIC: IS REVENUE
// ==========================================================

financialSchema.statics.isRevenue =
function(type) {

    return (
        normalizeFinancialType(
            type
        ) === "revenue"
    );

};


// ==========================================================
// STATIC: IS LIABILITY
// ==========================================================

financialSchema.statics.isLiability =
function(type) {

    return (
        normalizeFinancialType(
            type
        ) === "liability"
    );

};


// ==========================================================
// MODEL
// ==========================================================

const Financials =

    mongoose.models.Financials ||

    mongoose.model(
        "Financials",
        financialSchema
    );


// ==========================================================
// CONSTANT EXPORT
// ==========================================================

Financials.FINANCIAL_TYPES =
    FINANCIAL_TYPES;


// ==========================================================
// EXPORT
// ==========================================================

module.exports =
    Financials;