// ==========================================================
// models/financials.js
// ==========================================================

const mongoose = require("mongoose");


// ==========================================================
// CONSTANTS
// ==========================================================
//
// Financial transaction types.
//
// liability
//     Money owed / financial obligation.
//
// revenue
//     Money earned / received by the dairy, farm, animal,
//     structure, facility, equipment, or standalone asset.
//
// These are TRANSACTIONS and therefore can be date filtered.
// ==========================================================

const FINANCIAL_TYPES = [

    "liability",

    "revenue"

];


// ==========================================================
// SCHEMA
// ==========================================================

const financialSchema = new mongoose.Schema(

    {

        // ==================================================
        // DAIRY / ASSET
        // ==================================================
        //
        // The specific Dairy record to which this financial
        // transaction belongs.
        //
        // This can be:
        //
        // Negative code:
        //     Dairy Farm
        //
        // Positive code:
        //     Animal
        //
        // Null code:
        //     Structure / Facility / Equipment
        //
        // A farm itself can therefore have:
        //
        //     - liabilities
        //     - revenue
        //
        // independently from the assets inside the farm.
        // ==================================================

        dairy: {

            type:
                mongoose.Schema.Types.ObjectId,

            ref: "Dairy",

            required: true,

            index: true

        },


        // ==================================================
        // DAIRY CODE
        // ==================================================
        //
        // Snapshot of the Dairy code when the transaction
        // was recorded.
        //
        // This is NOT the primary relationship.
        //
        // The `dairy` ObjectId above remains authoritative.
        //
        // This is useful for historical/audit purposes.
        // ==================================================

        dairyCode: {

            type: Number,

            default: null

        },


        // ==================================================
        // FINANCIAL TYPE
        // ==================================================
        //
        // liability
        //     Financial obligation.
        //
        // revenue
        //     Income/revenue generated by the record.
        //
        // Both types are date-filtered during financial
        // reporting.
        // ==================================================

        type: {

            type: String,

            enum:
                FINANCIAL_TYPES,

            default:
                "liability",

            required: true,

            index: true

        },


        // ==================================================
        // AMOUNT
        // ==================================================
        //
        // Amount of the financial transaction.
        //
        // For liability:
        //
        //     amount = liability amount
        //
        // For revenue:
        //
        //     amount = revenue amount
        //
        // The meaning is determined by `type`.
        // ==================================================

        amount: {

            type: Number,

            required: true,

            min: 0

        },


        // ==================================================
        // DESCRIPTION
        // ==================================================
        //
        // Explanation of what the financial transaction
        // represents.
        //
        // Examples:
        //
        // Liability:
        //     Veterinary bill
        //     Feed purchased on credit
        //
        // Revenue:
        //     Milk sales
        //     Manure sales
        //     Service income
        // ==================================================

        description: {

            type: String,

            trim: true,

            required: true

        },


        // ==================================================
        // RECORDED BY
        // ==================================================
        //
        // User who recorded the financial transaction.
        // ==================================================

        recordedBy: {

            type:
                mongoose.Schema.Types.ObjectId,

            ref: "User",

            required: true,

            index: true

        },


        // ==================================================
        // RECORDED BY NAME
        // ==================================================
        //
        // Snapshot of the user's name at the time the
        // transaction was recorded.
        //
        // This allows historical records to continue showing
        // the recorder's name even if the user's profile
        // changes later.
        // ==================================================

        recordedByName: {

            type: String,

            trim: true,

            default: ""

        }

    },

    {

        // ==================================================
        // TIMESTAMPS
        // ==================================================
        //
        // createdAt:
        //     When the transaction was recorded.
        //
        // updatedAt:
        //     When the transaction was last changed.
        // ==================================================

        timestamps: true,

        minimize: false

    }

);


// ==========================================================
// INDEXES
// ==========================================================


// ==========================================================
// DAIRY + TYPE
// ==========================================================
//
// Useful when retrieving all liabilities or revenue belonging
// to a particular Dairy record.
// ==========================================================

financialSchema.index({

    dairy: 1,

    type: 1

});


// ==========================================================
// DAIRY + TYPE + CREATED AT
// ==========================================================
//
// Important for date-filtered financial calculations.
//
// Examples:
//
//     all liabilities for one asset in a period
//
//     all revenue for one asset in a period
// ==========================================================

financialSchema.index({

    dairy: 1,

    type: 1,

    createdAt: -1

});


// ==========================================================
// TYPE + CREATED AT
// ==========================================================
//
// Useful for summary calculations across all records.
//
// Examples:
//
//     all revenue within a selected period
//
//     all liabilities within a selected period
// ==========================================================

financialSchema.index({

    type: 1,

    createdAt: -1

});


// ==========================================================
// RECORDED BY + CREATED AT
// ==========================================================
//
// Useful for audit/history reporting.
// ==========================================================

financialSchema.index({

    recordedBy: 1,

    createdAt: -1

});


// ==========================================================
// STATIC: GET FINANCIAL TYPES
// ==========================================================

financialSchema.statics.getFinancialTypes =
function() {

    return [

        ...FINANCIAL_TYPES

    ];

};


// ==========================================================
// STATIC: CHECK FINANCIAL TYPE
// ==========================================================

financialSchema.statics.isFinancialType =
function(type) {

    return FINANCIAL_TYPES.includes(

        String(type || "")
            .trim()
            .toLowerCase()

    );

};


// ==========================================================
// MODEL
// ==========================================================

const Financials =

    mongoose.models.Financials ||

    mongoose.model(

        "Financials",

        financialSchema

    );


// ==========================================================
// CONSTANT EXPORT
// ==========================================================

Financials.FINANCIAL_TYPES =

    FINANCIAL_TYPES;


// ==========================================================
// EXPORT
// ==========================================================

module.exports = Financials;