// ==========================================================
// models/milk.js
// ==========================================================
//
// PURPOSE
// ----------------------------------------------------------
// Central Mongoose model for:
//
// • Milk production records
// • Morning / evening milking sessions
// • Animal-specific milk records
// • User/system recording attribution
// • Nairobi day/month reporting
// • Daily milk reports
// • Monthly milk reports
// • Milking history
//
// IMPORTANT
// ----------------------------------------------------------
// One animal can have:
//
//   1 morning record
//   1 evening record
//
// for each calendar day.
//
// The `day` and `month` fields are derived from `date` using
// Africa/Nairobi timezone.
//
// ==========================================================


const mongoose = require("mongoose");


// ==========================================================
// CONSTANTS
// ==========================================================

const NAIROBI_TIMEZONE =
    "Africa/Nairobi";

const SESSION_VALUES = [
    "morning",
    "evening"
];

const RECORDER_TYPE_VALUES = [
    "user",
    "system"
];


// ==========================================================
// DATE HELPERS
// ==========================================================
//
// These helpers are deliberately kept inside the model so
// that all milk records use exactly the same date logic.
//
// ==========================================================

function getNairobiDateParts(dateValue) {

    const date =
        new Date(dateValue);


    if (
        Number.isNaN(
            date.getTime()
        )
    ) {

        throw new Error(
            "Invalid milk record date."
        );

    }


    const formatter =
        new Intl.DateTimeFormat(
            "en-CA",
            {

                timeZone:
                    NAIROBI_TIMEZONE,

                year:
                    "numeric",

                month:
                    "2-digit",

                day:
                    "2-digit"

            }
        );


    const day =
        formatter.format(date);


    return {

        day,

        month:
            day.slice(
                0,
                7
            )

    };

}


// ==========================================================
// MAIN MILK SCHEMA
// ==========================================================

const milkSchema =
    new mongoose.Schema(

        {

            // ==================================================
            // COW / ANIMAL
            // ==================================================
            //
            // The individual Dairy animal that produced this
            // milk.
            //
            // ==================================================

            dairy: {

                type:
                    mongoose.Schema.Types.ObjectId,

                ref:
                    "Dairy",

                required:
                    true,

                index:
                    true

            },


            // ==================================================
            // WHO RECORDED THE MILK
            // ==================================================
            //
            // For normal user-entered records this contains
            // the User._id.
            //
            // For system-generated records this may be null.
            //
            // ==================================================

            recordedBy: {

                type:
                    mongoose.Schema.Types.ObjectId,

                ref:
                    "User",

                default:
                    null,

                index:
                    true

            },


            // ==================================================
            // RECORDER TYPE
            // ==================================================
            //
            // user   = entered by a user
            // system = generated by the application
            //
            // ==================================================

            recordedByType: {

                type:
                    String,

                enum:
                    RECORDER_TYPE_VALUES,

                default:
                    "user",

                index:
                    true

            },


            // ==================================================
            // BACKWARDS COMPATIBILITY
            // ==================================================
            //
            // Older service code may still use:
            //
            // recordedBySystem: true
            //
            // This field is retained so existing records and
            // services do not immediately break.
            //
            // New code should preferably use recordedByType.
            //
            // ==================================================

            recordedBySystem: {

                type:
                    Boolean,

                default:
                    false

            },


            // ==================================================
            // MILK QUANTITY
            // ==================================================

            liters: {

                type:
                    Number,

                required:
                    true,

                min:
                    0,

                validate: {

                    validator:
                        function(value) {

                            return (
                                Number.isFinite(
                                    value
                                )
                            );

                        },

                    message:
                        "Milk quantity must be a valid number."

                }

            },


            // ==================================================
            // REMARKS
            // ==================================================

            remarks: {

                type:
                    String,

                default:
                    "",

                trim:
                    true

            },


            // ==================================================
            // ACTUAL RECORD DATE
            // ==================================================
            //
            // This is the actual timestamp of the milk record.
            //
            // `day` and `month` are derived from this field.
            //
            // ==================================================

            date: {

                type:
                    Date,

                default:
                    Date.now,

                required:
                    true,

                index:
                    true

            },


            // ==================================================
            // NAIROBI DAY
            // ==================================================
            //
            // Format:
            //
            // YYYY-MM-DD
            //
            // Example:
            //
            // 2026-08-12
            //
            // ==================================================

            day: {

                type:
                    String,

                index:
                    true

            },


            // ==================================================
            // NAIROBI MONTH
            // ==================================================
            //
            // Format:
            //
            // YYYY-MM
            //
            // Example:
            //
            // 2026-08
            //
            // ==================================================

            month: {

                type:
                    String,

                index:
                    true

            },


            // ==================================================
            // MILKING SESSION
            // ==================================================

            session: {

                type:
                    String,

                enum:
                    SESSION_VALUES,

                required:
                    true,

                index:
                    true

            }

        },

        {

            // ==================================================
            // AUTOMATIC CREATED / UPDATED TIMESTAMPS
            // ==================================================

            timestamps:
                true,


            // ==================================================
            // KEEP EMPTY OBJECTS
            // ==================================================

            minimize:
                false

        }

    );


// ==========================================================
// NORMALIZE RECORDER INFORMATION
// ==========================================================
//
// Supports both:
//
//     recordedByType: "system"
//
// and the older:
//
//     recordedBySystem: true
//
// The old field takes precedence when explicitly true.
//
// ==========================================================

milkSchema.pre(
    "validate",
    function(next) {

        try {

            // --------------------------------------------------
            // Backwards-compatible system flag
            // --------------------------------------------------

            if (
                this.recordedBySystem === true
            ) {

                this.recordedByType =
                    "system";

            }


            // --------------------------------------------------
            // Explicit system type
            // --------------------------------------------------

            else if (
                this.recordedByType === "system"
            ) {

                this.recordedBySystem =
                    true;

            }


            // --------------------------------------------------
            // Normal user record
            // --------------------------------------------------

            else {

                this.recordedByType =
                    "user";

                this.recordedBySystem =
                    false;

            }


            // --------------------------------------------------
            // Normalize day/month from date
            // --------------------------------------------------

            const parts =
                getNairobiDateParts(
                    this.date
                );


            this.day =
                parts.day;


            this.month =
                parts.month;


            next();

        }

        catch (error) {

            next(error);

        }

    }
);


// ==========================================================
// UPDATE DATE KEYS
// ==========================================================
//
// Mongoose `save()` middleware does NOT automatically run
// when services use:
//
//     updateOne()
//     findOneAndUpdate()
//     findByIdAndUpdate()
//
// Therefore these middleware handlers keep `day` and `month`
// synchronized when the date is changed through an update.
//
// ==========================================================

function normalizeUpdateDateKeys(update) {

    if (
        !update ||
        typeof update !== "object"
    ) {

        return;

    }


    // --------------------------------------------------------
    // Determine whether date is being changed.
    // --------------------------------------------------------

    let dateValue =
        null;


    if (
        Object.prototype.hasOwnProperty.call(
            update,
            "date"
        )
    ) {

        dateValue =
            update.date;

    }

    else if (
        update.$set &&
        Object.prototype.hasOwnProperty.call(
            update.$set,
            "date"
        )
    ) {

        dateValue =
            update.$set.date;

    }


    // --------------------------------------------------------
    // No date change.
    // --------------------------------------------------------

    if (
        dateValue === null ||
        dateValue === undefined
    ) {

        return;

    }


    // --------------------------------------------------------
    // Calculate Nairobi keys.
    // --------------------------------------------------------

    const parts =
        getNairobiDateParts(
            dateValue
        );


    // --------------------------------------------------------
    // Ensure $set exists.
    // --------------------------------------------------------

    if (
        !update.$set
    ) {

        update.$set =
            {};

    }


    update.$set.day =
        parts.day;


    update.$set.month =
        parts.month;

}


// ==========================================================
// FIND ONE AND UPDATE
// ==========================================================

milkSchema.pre(
    "findOneAndUpdate",
    function(next) {

        try {

            const update =
                this.getUpdate();


            normalizeUpdateDateKeys(
                update
            );


            next();

        }

        catch (error) {

            next(error);

        }

    }
);


// ==========================================================
// UPDATE ONE
// ==========================================================

milkSchema.pre(
    "updateOne",
    function(next) {

        try {

            const update =
                this.getUpdate();


            normalizeUpdateDateKeys(
                update
            );


            next();

        }

        catch (error) {

            next(error);

        }

    }
);


// ==========================================================
// UPDATE MANY
// ==========================================================

milkSchema.pre(
    "updateMany",
    function(next) {

        try {

            const update =
                this.getUpdate();


            normalizeUpdateDateKeys(
                update
            );


            next();

        }

        catch (error) {

            next(error);

        }

    }
);


// ==========================================================
// DAILY REPORT
// ==========================================================
//
// Returns all milk records for a Nairobi calendar day.
//
// Example:
//
//     Milk.getDailyReport("2026-08-12")
//
// ==========================================================

milkSchema.statics.getDailyReport =
async function(day) {

    if (
        typeof day !== "string" ||
        !/^\d{4}-\d{2}-\d{2}$/.test(day)
    ) {

        throw new Error(
            "Daily milk report requires a valid day in YYYY-MM-DD format."
        );

    }


    const records =
        await this.find({

            day

        })

        .populate(
            "dairy"
        )

        .populate(
            "recordedBy",
            "name"
        )

        .sort({

            date:
                1,

            session:
                1

        })

        .lean();


    const total =
        records.reduce(

            (
                sum,
                record
            ) => {

                const liters =
                    Number(
                        record.liters
                    );


                return (
                    sum +
                    (
                        Number.isFinite(
                            liters
                        )
                            ? liters
                            : 0
                    )
                );

            },

            0

        );


    return {

        records,

        stats: {

            total

        }

    };

};


// ==========================================================
// MONTHLY REPORT
// ==========================================================
//
// Example:
//
//     Milk.getMonthlyReport("2026-08")
//
// Groups production by animal.
//
// `days` represents the number of distinct Nairobi calendar
// days on which that animal has milk records.
//
// `avg` is therefore:
//
//     total liters / number of recorded days
//
// ==========================================================

milkSchema.statics.getMonthlyReport =
async function(month) {

    if (
        typeof month !== "string" ||
        !/^\d{4}-\d{2}$/.test(month)
    ) {

        throw new Error(
            "Monthly milk report requires a valid month in YYYY-MM format."
        );

    }


    const grouped =
        await this.aggregate(

            [

                // ==========================================
                // MATCH MONTH
                // ==========================================

                {

                    $match: {

                        month

                    }

                },


                // ==========================================
                // GROUP BY ANIMAL
                // ==========================================

                {

                    $group: {

                        _id:
                            "$dairy",

                        total: {

                            $sum:
                                "$liters"

                        },

                        days: {

                            $addToSet:
                                "$day"

                        }

                    }

                },


                // ==========================================
                // CALCULATE AVERAGE
                // ==========================================

                {

                    $project: {

                        _id:
                            0,

                        dairy:
                            "$_id",

                        total:
                            1,

                        days:
                            1,

                        avg: {

                            $cond: [

                                {

                                    $gt: [

                                        {
                                            $size:
                                                "$days"
                                        },

                                        0

                                    ]

                                },

                                {

                                    $divide: [

                                        "$total",

                                        {
                                            $size:
                                                "$days"
                                        }

                                    ]

                                },

                                0

                            ]

                        }

                    }

                },


                // ==========================================
                // SORT HIGHEST PRODUCER FIRST
                // ==========================================

                {

                    $sort: {

                        total:
                            -1

                    }

                }

            ]

        );


    return {

        records:
            grouped

    };

};


// ==========================================================
// ANIMAL MONTHLY HISTORY
// ==========================================================
//
// Useful for milkingHistory.ejs.
//
// Returns every milk record for one animal during a given
// month.
//
// Example:
//
//     Milk.getAnimalMonthlyHistory(
//         dairyId,
//         "2026-08"
//     )
//
// ==========================================================

milkSchema.statics.getAnimalMonthlyHistory =
async function(
    dairyId,
    month
) {

    if (
        !mongoose.isValidObjectId(
            dairyId
        )
    ) {

        throw new Error(
            "Invalid dairy ID."
        );

    }


    if (
        typeof month !== "string" ||
        !/^\d{4}-\d{2}$/.test(month)
    ) {

        throw new Error(
            "Monthly history requires YYYY-MM format."
        );

    }


    const records =
        await this.find({

            dairy:
                dairyId,

            month

        })

        .populate(
            "dairy"
        )

        .populate(
            "recordedBy",
            "name"
        )

        .sort({

            day:
                -1,

            session:
                1,

            date:
                -1

        })

        .lean();


    const total =
        records.reduce(

            (
                sum,
                record
            ) => {

                const liters =
                    Number(
                        record.liters
                    );


                return (
                    sum +
                    (
                        Number.isFinite(
                            liters
                        )
                            ? liters
                            : 0
                    )
                );

            },

            0

        );


    return {

        records,

        stats: {

            total,

            count:
                records.length

        }

    };

};


// ==========================================================
// INDEXES
// ==========================================================
//
// IMPORTANT:
//
// One animal can have only:
//
//     morning + evening
//
// for a particular Nairobi calendar day.
//
// This prevents accidental duplicate milk entries.
//
// ==========================================================

milkSchema.index(

    {

        dairy:
            1,

        day:
            1,

        session:
            1

    },

    {

        unique:
            true,

        name:
            "unique_dairy_day_session"

    }

);


// ==========================================================
// MONTHLY ANIMAL LOOKUP
// ==========================================================

milkSchema.index(

    {

        dairy:
            1,

        month:
            1

    },

    {

        name:
            "dairy_month_lookup"

    }

);


// ==========================================================
// DAY + DATE REPORTING INDEX
// ==========================================================
//
// Useful for:
//
//     daily history
//     recent records
//     chronological reports
//
// ==========================================================

milkSchema.index(

    {

        day:
            1,

        date:
            -1

    },

    {

        name:
            "day_date_lookup"

    }

);


// ==========================================================
// RECORDER HISTORY INDEX
// ==========================================================

milkSchema.index(

    {

        recordedBy:
            1,

        date:
            -1

    },

    {

        name:
            "recorder_date_lookup"

    }

);


// ==========================================================
// MODEL
// ==========================================================
//
// Prevents OverwriteModelError during development when
// files are reloaded.
//
// ==========================================================

const Milk =
    mongoose.models.Milk ||
    mongoose.model(
        "Milk",
        milkSchema
    );


// ==========================================================
// EXPORT
// ==========================================================

module.exports =
    Milk;