// ==========================================================
// models/milkSummary.js
// ==========================================================

const mongoose = require("mongoose");


// ==========================================================
// DAILY SALE
// ==========================================================

const saleSchema = new mongoose.Schema({

  // --------------------------------------------------------
  // CUSTOMER
  // --------------------------------------------------------

  customerName: {

    type: String,

    required: true,

    trim: true

  },


  // --------------------------------------------------------
  // QUANTITY SOLD
  // --------------------------------------------------------

  liters: {

    type: Number,

    required: true,

    min: 0

  },


  // --------------------------------------------------------
  // PRICE PER LITER
  // --------------------------------------------------------

  price: {

    type: Number,

    required: true,

    default: 50,

    min: 0

  },


  // --------------------------------------------------------
  // REVENUE FROM THIS SALE
  // --------------------------------------------------------

  cash: {

    type: Number,

    required: true,

    default: 0,

    min: 0

  },


  // --------------------------------------------------------
  // STANDING ORDER
  // --------------------------------------------------------

  standingOrderId: {

    type:
      mongoose.Schema.Types.ObjectId,

    ref:
      "StandingOrder",

    default:
      null

  },


  // --------------------------------------------------------
  // SALE TIMESTAMP
  // --------------------------------------------------------

  createdAt: {

    type: Date,

    default: Date.now

  }

}, {

  _id: false

});


// ==========================================================
// DAILY FARM MILK SUMMARY
// ==========================================================

const milkSummarySchema = new mongoose.Schema({

  // ========================================================
  // FARM
  // ========================================================
  //
  // The Dairy document representing the farm.
  //
  // IMPORTANT:
  // Revenue and milk statistics are therefore associated
  // with a specific farm.
  //
  // ========================================================

  dairy: {

    type:
      mongoose.Schema.Types.ObjectId,

    ref:
      "Dairy",

    required: true

  },


  // ========================================================
  // DAY
  // ========================================================

  day: {

    type: String,

    required: true

  },


  // ========================================================
  // MONTH
  // ========================================================

  month: {

    type: String

  },


  // ========================================================
  // MILK PRICE
  // ========================================================

  price: {

    type: Number,

    default: 50,

    min: 0

  },


  // ========================================================
  // TOTAL MILK SOLD / CONSUMED
  // ========================================================

  consumed: {

    type: Number,

    default: 0,

    min: 0

  },


  // ========================================================
  // MILK REMAINING
  // ========================================================

  available: {

    type: Number,

    default: 0,

    min: 0

  },


  // ========================================================
  // TOTAL REVENUE
  // ========================================================
  //
  // This is the total revenue generated by THIS FARM
  // for THIS DAY.
  //
  // It is calculated from the sales array.
  //
  // ========================================================

  cash: {

    type: Number,

    default: 0,

    min: 0

  },


  // ========================================================
  // DAILY SALES
  // ========================================================

  sales: {

    type: [saleSchema],

    default: []

  },


  // ========================================================
  // DAILY SUMMARY LOCK
  // ========================================================

  locked: {

    type: Boolean,

    default: false

  }

}, {

  // ========================================================
  // AUTOMATIC DOCUMENT TIMESTAMPS
  // ========================================================
  //
  // Mongoose automatically creates:
  //
  // createdAt
  // updatedAt
  //
  // ========================================================

  timestamps: true

});


// ==========================================================
// UNIQUE FARM + DAY
// ==========================================================
//
// A farm can have only ONE summary document for a particular
// day.
//
// Example:
//
// Farm A + 2026-08-12  -> one summary
// Farm B + 2026-08-12  -> another summary
//
// ==========================================================

milkSummarySchema.index(

  {

    dairy: 1,

    day: 1

  },

  {

    unique: true

  }

);


// ==========================================================
// FARM + MONTH INDEX
// ==========================================================
//
// Helps monthly statistics and farm-specific queries.
//
// ==========================================================

milkSummarySchema.index({

  dairy: 1,

  month: 1

});


// ==========================================================
// SET MONTH FROM DAY
// ==========================================================

milkSummarySchema.pre(
  "save",
  function(next) {

    if (this.day) {

      this.month =
        this.day.slice(0, 7);

    }

    next();

  }
);


// ==========================================================
// EXPORT
// ==========================================================

module.exports =
  mongoose.model(
    "MilkSummary",
    milkSummarySchema
  );