const mongoose=require('mongoose'); const Stock=require('../models/stock'); const Product=require('../models/products'); const Substation=require('../models/substations');
const t=v=>String(v??'').trim();
function n(v,label,required=false){if(v===''||v==null){if(!required)return 0;throw Error(label+' is required.')}const x=Number(v);if(!Number.isFinite(x)||x<0)throw Error(label+' must be zero or greater.');return x}
function whole(v,label,required=false){const x=n(v,label,required);if(!Number.isInteger(x))throw Error(label+' must be a whole number.');return x}
exports.listStock=()=>Stock.find({isActive:true}).sort({category:1,name:1}).lean();
exports.getStock=id=>mongoose.isValidObjectId(id)?Stock.findById(id).lean():null;
exports.getSubstations=()=>Substation.find({isActive:true}).sort({name:1}).lean();
exports.createStock=body=>{const name=t(body.name),category=t(body.category).toLowerCase();if(!name||!category)throw Error('Stock name and category are required.');return Stock.create({name,category,image:t(body.image),units:whole(body.units,'Stock units',true),buyPrice:n(body.buyPrice,'Buy price'),description:t(body.description)})};
exports.createProductFromStock=async(stockId,body)=>{if(!mongoose.isValidObjectId(stockId))throw Error('Invalid stock.');const name=t(body.name),category=t(body.category).toLowerCase(),units=whole(body.units,'Product units',true),substationId=t(body.substation);if(!name||!category)throw Error('Product name and category are required.');if(units<=0)throw Error('Product units must be greater than zero.');if(substationId&&!mongoose.isValidObjectId(substationId))throw Error('Invalid substation.');const session=await mongoose.startSession();try{let product;await session.withTransaction(async()=>{const stock=await Stock.findById(stockId).session(session);if(!stock)throw Error('Stock not found.');if(units>stock.units)throw Error(`Only ${stock.units} units are available in stock.`);if(substationId){const s=await Substation.findOne({_id:substationId,isActive:true}).session(session);if(!s)throw Error('Selected substation was not found.')}[product]=await Product.create([{stock:stock._id,name,category,image:t(body.image),units,buyPrice:n(body.buyPrice,'Buy price'),unitSellPrice:n(body.unitSellPrice,'Selling price',true),description:t(body.description),substation:substationId||null}],{session});stock.units-=units;await stock.save({session});});return product}finally{await session.endSession()}};
